import json
import pandas as pd
import re

BASE = "/root/autodl-tmp/gen-depth-contamination"

cases = [
    {
        'label': 'A',
        'title': 'C4 Web Content (Stylistic Convergence)',
        'doc_id': 2468,
        'base': f'{BASE}/data_exp016_qwen_base',
        'desc': 'Vacation rental listing converges to generic real-estate prose.',
    },
    {
        'label': 'B',
        'title': 'C4 Encyclopedic (Factual Degradation)',
        'doc_id': 3000,
        'base': f'{BASE}/data_exp016_qwen_base',
        'desc': 'Historical stone description degrades into hallucinated legend.',
    },
    {
        'label': 'C',
        'title': 'arXiv (Domain-Specific Collapse)',
        'doc_id': 1079,
        'base': f'{BASE}/data/exp_024_arxiv',
        'desc': 'ML abstract collapses into acknowledgement boilerplate by depth~2.',
    },
]

def escape_latex(s):
    s = s.replace('\\', '\\textbackslash{}')
    s = s.replace('&', '\\&')
    s = s.replace('%', '\\%')
    s = s.replace('$', '\\$')
    s = s.replace('#', '\\#')
    s = s.replace('_', '\\_')
    s = s.replace('{', '\\{')
    s = s.replace('}', '\\}')
    s = s.replace('~', '\\textasciitilde{}')
    s = s.replace('^', '\\textasciicircum{}')
    s = s.replace('"', "''")
    # Fix double-escaped textbackslash
    s = s.replace('\\textbackslash\\{\\}', '\\textbackslash{}')
    return s

def get_text(path, doc_id, max_words=80):
    with open(path) as f:
        for line in f:
            d = json.loads(line)
            if d['doc_id'] == doc_id:
                text = d['text']
                words = text.split()[:max_words]
                result = ' '.join(words)
                if len(words) < len(text.split()):
                    result += ' [...]'
                return result
    return ''

def get_features(csv_path, doc_id):
    df = pd.read_csv(csv_path)
    doc = df[df['doc_id'] == doc_id].sort_values('depth')
    feats = {}
    for _, r in doc[doc['depth'] <= 3].iterrows():
        d = int(r['depth'])
        feats[d] = {
            'ttr': r['ttr'],
            'surp_mean': r['surp_mean'],
            'freq_entropy': r['freq_entropy'],
            'hapax_ratio': r['hapax_ratio'],
        }
    return feats

# Build LaTeX
lines = []
lines.append(r'\begin{figure*}[t]')
lines.append(r'\centering')

for ci, case in enumerate(cases):
    doc_id = case['doc_id']
    feat_path = f"{case['base']}/features.csv"
    feats = get_features(feat_path, doc_id)
    
    if ci > 0:
        lines.append(r'\vspace{0.8em}')
        lines.append(r'\noindent\rule{\textwidth}{0.4pt}')
        lines.append(r'\vspace{0.4em}')
    
    lines.append(r'\noindent\textbf{Case ' + case['label'] + ': ' + case['title'] + r'}')
    lines.append(r'\vspace{0.3em}')
    lines.append('')
    lines.append(r'\noindent{\small ' + case['desc'] + r'}')
    lines.append(r'\vspace{0.3em}')
    lines.append('')
    
    # Feature summary table (compact inline)
    lines.append(r'\noindent{\footnotesize')
    lines.append(r'\begin{tabular}{lcccc}')
    lines.append(r'\toprule')
    lines.append(r'& Depth 0 & Depth 1 & Depth 2 & Depth 3 \\')
    lines.append(r'\midrule')
    
    for fname, display in [('ttr', 'TTR'), ('surp_mean', 'Mean Surp.'), ('freq_entropy', 'Freq. Ent.')]:
        vals = []
        for d in range(4):
            v = feats[d][fname]
            vals.append(f'{v:.3f}')
        lines.append(f'{display} & ' + ' & '.join(vals) + r' \\')
    
    lines.append(r'\bottomrule')
    lines.append(r'\end{tabular}}')
    lines.append(r'\vspace{0.3em}')
    lines.append('')
    
    # Text excerpts
    for depth in range(4):
        text = get_text(f"{case['base']}/depth_{depth}.jsonl", doc_id, max_words=60)
        escaped = escape_latex(text)
        depth_label = f'Depth {depth}'
        if depth == 0:
            depth_label += ' (human)'
        lines.append(r'\noindent\textsc{' + depth_label + r'}: {\small\itshape ' + escaped + r'}')
        lines.append('')

lines.append(r'\caption{Qualitative case study: text excerpts across generation depths 0--3 for three representative documents.')
lines.append(r'Case~A and B use C4 data generated by Qwen-1.5B; Case~C uses arXiv data.')
lines.append(r'Feature values (TTR, Mean Surprisal, Frequency Entropy) are computed by a Qwen-1.5B scorer.')
lines.append(r'Depth~0 is the original human text; each subsequent depth is generated by prompting the model with the previous depth.')
lines.append(r'In Cases~A and B, features converge sharply after depth~1, consistent with $K^*{=}2$.')
lines.append(r'In Case~C, the arXiv text retains more structure at depth~1 but collapses into boilerplate acknowledgements by depth~2.}')
lines.append(r'\label{fig:case-study}')
lines.append(r'\end{figure*}')

latex = '\n'.join(lines)
out_path = f"{BASE}/artifacts/case_study_qualitative.tex"
with open(out_path, 'w') as f:
    f.write(latex)

print(f"Written to {out_path}")
print(f"Total lines: {len(lines)}")
print("\n--- Preview (first 30 lines) ---")
for l in lines[:30]:
    print(l)
